name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Restore Dependencies
      run: dotnet restore BloodPressureTracker2.sln

    - name: Build Project
      run: dotnet build BloodPressureTracker2.sln --no-restore

    - name: Run Tests
      run: dotnet test BloodPressureTracker2.sln --no-build --verbosity normal